apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab28-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/quangha-dev/TRACK2_Day28_2A202601424_NguyenQuangHa.git
    targetRevision: b3c323daec70e6444b393c017b9d47e66c65a0f7
    path: deploy/kubernetes/base
  destination:
    server: https://kubernetes.default.svc
    namespace: lab28
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 5
